OUTPUT=vlcbdefs.inc
echo "Generating $OUTPUT"
# first out put the header stuff
cat << EOF > $OUTPUT
; DO NOT EDIT THIS FILE.
; This file is automatically generated by $0 from vlcb-defs.csv

EOF
# now output the actual contents
while IFS="," read type name value comment
do
    if [ "$type" = "comment" ]; then
        echo -e "; $name\t$value\t$comment"
    else
        type=${type/#Cbus/Vlcb}
        if [ "X$name" = "X" ]; then
            echo -e "; $value$comment"
        else
            start=`echo -e $value | cut -c1-2 | tr "x" "X"`
            if [ "x$start" = "x0X" ]; then
                echo -e "$name\tequ $value\t; $comment"
            else
                echo -e "$name\tequ .$value\t; $comment"
            fi
        fi
    fi
done < vlcb-defs.csv >>$OUTPUT

# finally output the trailer stuff
# none needed
