OUTPUT=vlcbdefs.py
echo "Generating $OUTPUT"
# first out put the header stuff
cat << EOF > $OUTPUT
# DO NOT EDIT THIS FILE.
# This file is automatically generated by $0 from vlcb-defs.csv
#

from micropython import const

EOF
# now output the actual contents
while IFS="," read type	name value comment
do
	if [ "$type" = "comment" ]; then
		echo -e "# $name    $value    $comment"
	else
		if [ "X$name" = "X" ]; then
			echo -e "# $value$comment"
		else
			echo -e "$name = const($value)    # $comment"
		fi
	fi
done < vlcb-defs.csv >>$OUTPUT

# finally output the trailer stuff
# there is none for Python
