OUTPUT=vlcbdefs.pas
echo "Generating $OUTPUT"
# first out put the header stuff
cat << EOF > $OUTPUT
{ DO NOT EDIT THIS FILE.
  This file is automatically generated by $0 from vlcb-defs.csv
}
unit vlcbdefs;

interface

const

EOF
# now output the actual contents
while IFS="," read type	name value comment
do
	if [ "$type" = "comment" ]; then
		echo -e "{ $name\t$value\t$comment }"
	else
		if [ "X$name" = "X" ]; then
			echo -e "// $value$comment"
		else
			echo -e " $name\t=  $value;\t// $comment"
		fi
	fi
done < vlcb-defs.csv >>$OUTPUT

# finally output the trailer stuff
cat << EOF >> $OUTPUT

implementation

end.
EOF
