/* DO NOT EDIT THIS FILE.
 * This file is automatically generated by ./generate.sh from vlcb-defs.csv
 */ 

package uk.org.merg.cbus;

// Copyright (C) Sven Rosvall (sven@rosvall.ie)
// This file is part of VLCB-Arduino project on https://github.com/SvenRosvall/VLCB-Arduino
// Licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
// The full licence can be found at: http://creativecommons.org/licenses/by-nc-sa/4.0/

public enum CbusSprogModuleTypes {
// 
// Sprog Module types
// 
	MTYP_CANPiSPRG3(1),	//Pi-SPROG 3 programmer/command station
	MTYP_CANSPROG3P(2),	//SPROG 3 Plus programmer/command station
	MTYP_CANSPROG(3),	//CAN SPROG programmer/command station
	MTYP_CANSBOOST(4),	//System Booster
	MTYP_CANPiSPRGP(5),	//Pi-SPROG 3 Plus programmer/command station
	MTYP_CANISB(6),	//CAN ISB Isolated CAN USB Interface
	MTYP_CANIO(7),	//8-channel I/O module
	MTYP_CANSERVOIO(8),	//8-channel Servo I/O module
	MTYP_CANSOLIO(9);	//8-channel (4-pairs) Solenoid I/O module

	private final int v;

	private CbusSprogModuleTypes(int v) {
		this.v = v;
	}

	public int value() {
		return v;
	}
}
