/* DO NOT EDIT THIS FILE.
 * This file is automatically generated by ./generate_java.sh from vlcb-defs.csv
 */

package uk.org.merg.vlcb;

// Copyright (C) Sven Rosvall (sven@rosvall.ie)
// This file is part of VLCB-Arduino project on https://github.com/SvenRosvall/VLCB-Arduino
// Licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
// The full licence can be found at: http://creativecommons.org/licenses/by-nc-sa/4.0/

public enum CbusSpectrumModuleTypes {
// 
// Spectrum Engineering Animated Modeller module types
// 
	MTYP_AMCTRLR(1),	//Animation controller (firmware derived from cancmd)
	MTYP_DUALCAB(2);	//Dual cab based on cancab

	private final int v;

	private CbusSpectrumModuleTypes(int v) {
		this.v = v;
	}

	public int value() {
		return v;
	}
}
