/* DO NOT EDIT THIS FILE.
 * This file is automatically generated by ./generate_java.sh from vlcb-defs.csv
 */

package uk.org.merg.vlcb;

// Copyright (C) Sven Rosvall (sven@rosvall.ie)
// This file is part of VLCB-Arduino project on https://github.com/SvenRosvall/VLCB-Arduino
// Licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
// The full licence can be found at: http://creativecommons.org/licenses/by-nc-sa/4.0/

public enum CbusErrs {
// 
// Error codes for OPC_ERR
// 
	ERR_LOCO_STACK_FULL(1),	//
	ERR_LOCO_ADDR_TAKEN(2),	//
	ERR_SESSION_NOT_PRESENT(3),	//
	ERR_CONSIST_EMPTY(4),	//
	ERR_LOCO_NOT_FOUND(5),	//
	ERR_CMD_RX_BUF_OFLOW(6),	//
	ERR_INVALID_REQUEST(7),	//
	ERR_SESSION_CANCELLED(8);	//

	private final int v;

	private CbusErrs(int v) {
		this.v = v;
	}

	public int value() {
		return v;
	}
}
