/* DO NOT EDIT THIS FILE.
 * This file is automatically generated by ./generate_java.sh from vlcb-defs.csv
 */

package uk.org.merg.vlcb;

// Copyright (C) Sven Rosvall (sven@rosvall.ie)
// This file is part of VLCB-Arduino project on https://github.com/SvenRosvall/VLCB-Arduino
// Licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
// The full licence can be found at: http://creativecommons.org/licenses/by-nc-sa/4.0/

public enum CbusParamOffsetsPic {
// 
// Offsets to other values stored at the top of the parameter block.
// These are not returned by opcode PARAN, but are present in the hex
// file for FCU.
// 
	PAR_COUNT(0x18),	//Number of parameters implemented
	PAR_NAME(0x1A),	//4 byte Address of Module type name, up to 8 characters null terminated
	PAR_CKSUM(0x1E);	//Checksum word at end of parameters

	private final int v;

	private CbusParamOffsetsPic(int v) {
		this.v = v;
	}

	public int value() {
		return v;
	}
}
