/* DO NOT EDIT THIS FILE.
 * This file is automatically generated by ./generate_java.sh from vlcb-defs.csv
 */

package uk.org.merg.vlcb;

// Copyright (C) Sven Rosvall (sven@rosvall.ie)
// This file is part of VLCB-Arduino project on https://github.com/SvenRosvall/VLCB-Arduino
// Licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
// The full licence can be found at: http://creativecommons.org/licenses/by-nc-sa/4.0/

public enum VlcbProcessorManufacturers {
// 
// Processor manufacturer codes
// 
	CPUM_MICROCHIP(1),	//
	CPUM_ATMEL(2),	//
	CPUM_ARM(3);	//

    private final int v;

    private VlcbProcessorManufacturers(int v) {
        this.v = v;
    }

    public int value() {
        return v;
    }
}
