/* DO NOT EDIT THIS FILE.
 * This file is automatically generated by ./generate_java.sh from vlcb-defs.csv
 */

package uk.org.merg.vlcb;

// Copyright (C) Sven Rosvall (sven@rosvall.ie)
// This file is part of VLCB-Arduino project on https://github.com/SvenRosvall/VLCB-Arduino
// Licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
// The full licence can be found at: http://creativecommons.org/licenses/by-nc-sa/4.0/

public enum VlcbBootloaderType {
// 
// Boot service reports of the module bootloader type
// 
	BL_TYPE_Unknown(0),	//Unknown or not specified
	BL_TYPE_MikeBolton(1),	//Original bootloader from Mike Bolton, Roger Healey, Pete Brownlow and others written in PIC assembler
	BL_TYPE_KonradOrlowski(2),	// Konrad (syspixie) bootloader written in XC8
	BL_TYPE_IanHogg(3);	// Ian Hogg bootloader written in XC8

    private final int v;

    private VlcbBootloaderType(int v) {
        this.v = v;
    }

    public int value() {
        return v;
    }
}
