/* DO NOT EDIT THIS FILE.
 * This file is automatically generated by ./generate_java.sh from vlcb-defs.csv
 */

package uk.org.merg.vlcb;

// Copyright (C) Sven Rosvall (sven@rosvall.ie)
// This file is part of VLCB-Arduino project on https://github.com/SvenRosvall/VLCB-Arduino
// Licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
// The full licence can be found at: http://creativecommons.org/licenses/by-nc-sa/4.0/

public enum VlcbSprogModuleTypes {
// 
// Sprog Module types
// 
	MTYP_CANPiSPRG3(1),	//Pi-SPROG 3 programmer/command station
	MTYP_CANSPROG3P(2),	//SPROG 3 Plus programmer/command station
	MTYP_CANSPROG(3),	//CAN SPROG programmer/command station
	MTYP_CANSBOOST(4),	//System Booster
	MTYP_CANPiSPRGP(5),	//Pi-SPROG 3 Plus programmer/command station
	MTYP_CANSOLNOID (8),	//8-channel (4-pairs) Solenoid I/O module
	MTYP_CANSERVOIO(50),	//8-channel Servo I/O module
	MTYP_CANISB(100),	//CAN ISB Isolated CAN USB Interface
	MTYP_CANSOLIO (101);	//8-channel (4-pairs) Solenoid I/O module

    private final int v;

    private VlcbSprogModuleTypes(int v) {
        this.v = v;
    }

    public int value() {
        return v;
    }
}
