/* DO NOT EDIT THIS FILE.
 * This file is automatically generated by ./generate_java.sh from vlcb-defs.csv
 */

package uk.org.merg.vlcb;

// Copyright (C) Sven Rosvall (sven@rosvall.ie)
// This file is part of VLCB-Arduino project on https://github.com/SvenRosvall/VLCB-Arduino
// Licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
// The full licence can be found at: http://creativecommons.org/licenses/by-nc-sa/4.0/

public enum VlcbCANID {
// 
// CANIDs allocated as fixed values
// Note that all new modules, or new firmware for existing modules, should obtain a CANID using self enumeration and implement
// automatic CANID conflict resolution, so that eventually we can remove the need for fixed CANIDs
// 
	CANID_CANCMD(0x72),	//(114) Fixed CANID for CANCMD or CANCSB
	CANID_CANUSB(0x7C),	//(124) Fixed CANID for CANUSB, although in current firmware it may just use the CANID from the sending software
	CANID_FCU(0x7D),	//(125) Default CANID used by FCU. Can be changed in settings. Note some interface modules may substitute their own CANID.
	CANID_JMRI(0x7E),	//(126) Default CANID used by JMRI. Can be changed in connection preferences. Note some interface modules may substitute their own CANID.
	CANID_CANEther(0x7F);	//(127) Default fixed CANID for CANEther (can be changed by modifying NV2). Note CANEther inserts its own CANID on all packets transmitted on CAN

    private final int v;

    private VlcbCANID(int v) {
        this.v = v;
    }

    public int value() {
        return v;
    }
}
