/* DO NOT EDIT THIS FILE.
 * This file is automatically generated by ./generate_java.sh from vlcb-defs.csv
 */

package uk.org.merg.vlcb;

// Copyright (C) Sven Rosvall (sven@rosvall.ie)
// This file is part of VLCB-Arduino project on https://github.com/SvenRosvall/VLCB-Arduino
// Licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
// The full licence can be found at: http://creativecommons.org/licenses/by-nc-sa/4.0/

public enum VlcbManufacturer {
// Manufacturer definitions
// Where the manufacturer already has an NMRA code, this is used
// 
	MANU_DEV(13),	//For new manufacturer development - who don't have a manufacturer id yet
	MANU_MERG(165),	//https://www.merg.co.uk
	MANU_SPROG(44),	//https://www.sprog-dcc.co.uk/
	MANU_ROCRAIL(70),	//http://www.rocrail.net
	MANU_SPECTRUM(80),	//http://animatedmodeler.com  (Spectrum Engineering)
	MANU_MERG_VLCB(250),	//range of MERG VLCB modules
	MANU_VLCB(250),	//range of MERG VLCB modules (Deprecated in favour of MANU_MERG_VLCB)
	MANU_SYSPIXIE(249),	//Konrad Orlowski
	MANU_RME(248);	//http://rmeuk.com  (Railway Modelling Experts Limited)

	private final int v;

	private VlcbManufacturer(int v) {
		this.v = v;
	}

	public int value() {
		return v;
	}
}
