/* DO NOT EDIT THIS FILE.
 * This file is automatically generated by ./generate_java.sh from vlcb-defs.csv
 */

package uk.org.merg.vlcb;

// Copyright (C) Sven Rosvall (sven@rosvall.ie)
// This file is part of VLCB-Arduino project on https://github.com/SvenRosvall/VLCB-Arduino
// Licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
// The full licence can be found at: http://creativecommons.org/licenses/by-nc-sa/4.0/

public enum VlcbCmdErrs {
// 
// Error codes for OPC_CMDERR
// 
	CMDERR_INV_CMD(1),	//Invalid command
	CMDERR_NOT_LRN(2),	//Not in learn mode
	CMDERR_NOT_SETUP(3),	//Not in setup mode
	CMDERR_TOO_MANY_EVENTS(4),	//Too many events
	CMDERR_NO_EV(5),	//No EV
	CMDERR_INV_EV_IDX(6),	//Invalid EV index
	CMDERR_INVALID_EVENT(7),	//Invalid event
	CMDERR_INV_EN_IDX(8),	//now reserved
	CMDERR_INV_PARAM_IDX(9),	//Invalid param index
	CMDERR_INV_NV_IDX(10),	//Invalid NV index
	CMDERR_INV_EV_VALUE(11),	//Invalid EV value
	CMDERR_INV_NV_VALUE(12),	//Invalid NV value
// 
// Additional error codes proposed and/or agreed but not yet in the current published specification
// 
	CMDERR_LRN_OTHER(13);	//Sent when module in learn mode sees NNLRN for different module (also exits learn mode) 
// 

	private final int v;

	private VlcbCmdErrs(int v) {
		this.v = v;
	}

	public int value() {
		return v;
	}
}
