/* DO NOT EDIT THIS FILE.
 * This file is automatically generated by ./generate_java.sh from vlcb-defs.csv
 */

package uk.org.merg.vlcb;

// Copyright (C) Sven Rosvall (sven@rosvall.ie)
// This file is part of VLCB-Arduino project on https://github.com/SvenRosvall/VLCB-Arduino
// Licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
// The full licence can be found at: http://creativecommons.org/licenses/by-nc-sa/4.0/

public enum VlcbCabSigAspect1 {
// 
// Aspect codes for CDAT_CABSIG
// 
// First aspect byte
// 
	SASP_DANGER(0),	//
	SASP_CAUTION(1),	//
	SASP_PRELIM_CAUTION(2),	//
	SASP_PROCEED(3),	//
	SASP_CALLON(4),	//Set bit 2 for call-on - main aspect will usually be at danger
	SASP_THEATRE(8);	//Set bit 3 to 0 for upper nibble is feather lcoation, set 1 for upper nibble is theatre code

	private final int v;

	private VlcbCabSigAspect1(int v) {
		this.v = v;
	}

	public int value() {
		return v;
	}
}
